apiVersion: v1
kind: ReplicationController
metadata:
 name: jenkins-rc
spec:
  replicas: 5
  selector:
    app: jenkins
  template:
    metadata:
     labels:
      app: jenkins
    spec:
     containers:
      - image: jenkins
        name:  my-jenkis
        ports:
        - containerPort: 8080
          protocol: TCP