apiVersion: v1
kind: Pod
metadata:
    name: busybox
spec:
  volumes:
       - name: hostvalume
         persistentVolumeClaim:
           claimName:  pvc-hostpath
  containers:
       - image: busybox
         name: busybox
         command: ["/bin/sh"]
         args: ["-c", "while true; do echo hello; sleep 6000;done"]
         volumeMounts:
           - name: hostvalume
             mountPath: /mydata
