apiVersion: v1
kind: Service
metadata:
  name:  sample-svc
  lables: 
    app: jenkins
spec:
  selector:
    app:  jenkins
  type: NodePort
  ports:
  - port:  8080
    protocol: TCP
    nodePort:  30008
