apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - image: tomcat:8
          name: tomcat
          ports:
            - containerPort: 8080
              protocol: TCP
